### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by tannoliu** [chen3feng/typhoon-blade#142]
hi,  新手试用blade（刚安装的），build报错如下
blade/blade.zip/blade_platform.py", line 97, in _get_java_include
    version_line = stderr.splitlines(True)[0]
IndexError: list index out of range

请问是什么原因？ 

难道和java 版本有关系？ 服务器默认是1.5的

**Comment by c9n** [comment]
`java -version` 看下输出是什么

**Comment by chen3feng** [comment]
可能是1.0的版本信息输出到stdout吗？请帮忙确认一下？

**Comment by chen3feng** [comment]
java不同版本输出版本号到stderr或者stdout，已经修正

**Comment by ben741863140** [comment]
遇到了同样的问题

**Comment by ben741863140** [comment]
Blade(error): Traceback (most recent call last):
  File "/root/blade-build/src/blade/blade_main.py", line 616, in main
    exit_code = _main(blade_path, argv)
  File "/root/blade-build/src/blade/blade_main.py", line 588, in _main
    return run_subcommand(command, options, targets, blade_path, build_dir)
  File "/root/blade-build/src/blade/blade_main.py", line 498, in run_subcommand
    command)
  File "/root/blade-build/src/blade/build_manager.py", line 594, in initialize
    blade_options, command)
  File "/root/blade-build/src/blade/build_manager.py", line 107, in __init__
    self.__build_toolchain = ToolChain()
  File "/root/blade-build/src/blade/toolchain.py", line 115, in __init__
    self.nvcc_version = self._get_nvcc_version()
  File "/root/blade-build/src/blade/toolchain.py", line 167, in _get_nvcc_version
    version = version_line.split()[5]
IndexError: list index out of range

Blade(error): Failure
