### ISSUE TITLE
#437(Cleanup code, remove-scons-cache-and-dccc) introduced a bug

### ISSUE THREAD

**Issue by WindLeeWT** [chen3feng/typhoon-blade#438]
#437 Assign to @chen3feng for a look

Blade(error): Traceback (most recent call last):
  File "thirdparty/blade/blade.zip/blade_main.py", line 528, in main
    exit_code = _main(blade_path)
  File "thirdparty/blade/blade.zip/blade_main.py", line 519, in _main
    return run_subcommand(command, options, targets, blade_path, build_dir)
  File "thirdparty/blade/blade.zip/blade_main.py", line 451, in run_subcommand
    blade.blade.generate()
  File "thirdparty/blade/blade.zip/blade.py", line 141, in generate
    self.generate_build_rules()
  File "thirdparty/blade/blade.zip/blade.py", line 134, in generate_build_rules
    rules = generator.generate_build_script()
  File "thirdparty/blade/blade.zip/rules_generator.py", line 830, in generate_build_script
    rules = self.generate_build_rules()
  File "thirdparty/blade/blade.zip/rules_generator.py", line 856, in generate_build_rules
    rules = self.scons_script_header_generator.generate(self.blade_path)
  File "thirdparty/blade/blade.zip/rules_generator.py", line 368, in generate
    self.generate_compliation_flags()
  File "thirdparty/blade/blade.zip/rules_generator.py", line 275, in generate_compliation_flags
    ld_env_str = 'LINK="%s"' % ld_str
NameError: global name 'ld_str' is not defined

**Comment by chen3feng** [comment]
TO BE FIXED

**Comment by chen3feng** [comment]
Fixed
